version: '3.5'
services:
  redis:
    image: "redis:alpine"
    container_name: "some-redis"
    ports:
      - "6379:6379"
#    networks:
#      - docker-network
#
#  aiohttp-server:
#    build: .
#    volumes:
#      - .:/src
#    working_dir: /src
#    command: >
#      bash -c "
#      python3 scraper.py
#      && python3 server.py"
#    ports:
#        - "8080:8080"
#    environment:
#        - redis_host=redis
#    depends_on:
#      - redis
#    networks:
#      - docker-network
#
#networks:
#  docker-network:
#    name: betinvest-net